# Request 1 processors on 1 node
#PBS -l nodes=1:ppn=1

#Request x number of hours of walltime
#PBS -l walltime=04:00:00

#Request 7 gigabyte of memory per process
#PBS -l mem=15gb

#Request that regular output and terminal output go to the same file
#PBS -j oe
#PBS -m abe

date
cd /mnt/nfs/arginine/data1/resAndStdt/transRegVar/exrna/bedgraphs


module load BEDTools

bedtools subtract -a resources-broad-hg38-v0-Homo_sapiens_assembly38.bed -b unionbedg/regionsNeeded.sorted.merged.bed > unionbedg/regions2mask.bed

bedtools maskfasta -fi ../refGenome/hg19/resources-broad-hg38-v0-Homo_sapiens_assembly38.fasta -bed unionbedg/regions2mask.bed -fo ../diRef/hg19.ERCC.AS.cov.masked.fasta



date

